[package]
name = "rt-gate"
version = "0.1.1"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/gate"
homepage = "https://github.com/ararog/gate"
description = "A tiny wrapper for async runtimes."
readme = "README.md"
license = "MIT"
keywords = ["tasks", "async", "runtime", "wrapper"]
publish = true
rust-version = "1.64.0"

[features]
default = ["tokio-rt"]

smol-rt = ["dep:smol"]
tokio-rt = ["dep:tokio"]

[dependencies]
smol = { version = "2.0.2", optional = true }
tokio = { version = "1.49.0", features = ["rt-multi-thread"], default-features = false, optional = true }
