[package]
name = "gate"
version = "0.1.0"
edition = "2024"

[features]
default = ["tokio-rt"]

smol-rt = ["dep:smol"]
tokio-rt = ["dep:tokio"]

[dependencies]
smol = { version = "2.0.2", optional = true }
tokio = { version = "1.49.0", features = ["rt-multi-thread"], default-features = false, optional = true }
